version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: "daily"
  # Maintain dependencies for composer
  - package-ecosystem: composer
    open-pull-requests-limit: 20
    directory: '/'
    schedule:
      interval: "daily"
